window.DEFAULT_HEADLINES = [
  // ============================================================
  // BULLISH / LONG (~80)
  // ============================================================

  // Mega-cap earnings beats
  { text: "Apple reports record Q3 revenue beating Wall Street estimates", ticker: "AAPL", direction: "long" },
  { text: "Apple iPhone sales surge 18% in China reversing decline trend", ticker: "AAPL", direction: "long" },
  { text: "Apple Services revenue hits all-time high of $24B in quarter", ticker: "AAPL", direction: "long" },
  { text: "Microsoft beats on both top and bottom line, cloud growth accelerates", ticker: "MSFT", direction: "long" },
  { text: "Microsoft Azure revenue grows 42% crushing consensus estimates", ticker: "MSFT", direction: "long" },
  { text: "Microsoft wins $22B Army headset contract over 10 years", ticker: "MSFT", direction: "long" },
  { text: "Alphabet reports blowout earnings driven by Google Cloud growth", ticker: "GOOGL", direction: "long", altTickers: ["GOOG"] },
  { text: "Google Search ad revenue jumps 15% year-over-year in Q2", ticker: "GOOGL", direction: "long", altTickers: ["GOOG"] },
  { text: "Amazon Web Services revenue jumps 35% year-over-year", ticker: "AMZN", direction: "long" },
  { text: "Amazon Prime membership surges to 250 million globally", ticker: "AMZN", direction: "long" },
  { text: "Amazon ad business crosses $50B annual run rate", ticker: "AMZN", direction: "long" },
  { text: "Meta Platforms ad revenue surges 25% as Reels monetization ramps", ticker: "META", direction: "long" },
  { text: "Meta Reality Labs losses narrow significantly beating expectations", ticker: "META", direction: "long" },

  // AI / Semiconductors
  { text: "NVIDIA raises full-year guidance on surging AI chip demand", ticker: "NVDA", direction: "long" },
  { text: "NVIDIA data center revenue triples year-over-year to $18.4B", ticker: "NVDA", direction: "long" },
  { text: "NVIDIA announces next-gen Blackwell chips shipping ahead of schedule", ticker: "NVDA", direction: "long" },
  { text: "AMD secures major AI chip deal with Microsoft Azure", ticker: "AMD", direction: "long" },
  { text: "AMD MI300X GPU gains significant market share in data centers", ticker: "AMD", direction: "long" },
  { text: "Broadcom reports blowout quarter on AI networking chip demand", ticker: "AVGO", direction: "long" },
  { text: "Broadcom custom AI chip orders surge from hyperscaler clients", ticker: "AVGO", direction: "long" },
  { text: "Marvell Technology wins major 5G infrastructure contract", ticker: "MRVL", direction: "long" },
  { text: "Taiwan Semiconductor raises capex forecast citing overwhelming AI demand", ticker: "TSM", direction: "long" },
  { text: "Arm Holdings reports 50% revenue growth on AI chip licensing boom", ticker: "ARM", direction: "long" },
  { text: "Micron announces $15 billion Idaho chip manufacturing plant", ticker: "MU", direction: "long" },
  { text: "Qualcomm wins Apple modem chip contract extension through 2027", ticker: "QCOM", direction: "long" },

  // EV / Auto
  { text: "Tesla delivers record 500K vehicles in Q4 exceeding expectations", ticker: "TSLA", direction: "long" },
  { text: "Tesla FSD autonomous driving gets regulatory approval in California", ticker: "TSLA", direction: "long" },
  { text: "Tesla energy storage deployments triple as Megapack demand soars", ticker: "TSLA", direction: "long" },
  { text: "Rivian secures $5B joint venture deal with Volkswagen", ticker: "RIVN", direction: "long" },

  // Streaming / Social
  { text: "Netflix adds 13 million subscribers crushing analyst forecasts", ticker: "NFLX", direction: "long" },
  { text: "Netflix ad-supported tier reaches 40 million monthly users", ticker: "NFLX", direction: "long" },
  { text: "Spotify premium subscribers jump 20% as price hikes stick", ticker: "SPOT", direction: "long" },

  // Financials
  { text: "JPMorgan reports record annual profit on strong trading revenue", ticker: "JPM", direction: "long" },
  { text: "JPMorgan net interest income beats by $800M on higher rates", ticker: "JPM", direction: "long" },
  { text: "Goldman Sachs trading revenue surges 40% in volatile markets", ticker: "GS", direction: "long" },
  { text: "Morgan Stanley wealth management AUM hits record $7 trillion", ticker: "MS", direction: "long" },
  { text: "Visa cross-border transaction volume jumps 20% on travel recovery", ticker: "V", direction: "long" },
  { text: "Mastercard beats estimates as consumer spending remains resilient", ticker: "MA", direction: "long" },

  // Healthcare / Biotech
  { text: "Eli Lilly obesity drug shows 25% weight loss in late-stage trial", ticker: "LLY", direction: "long" },
  { text: "Eli Lilly Mounjaro approved for sleep apnea expanding addressable market", ticker: "LLY", direction: "long" },
  { text: "Moderna flu-COVID combo vaccine shows strong Phase 3 results", ticker: "MRNA", direction: "long" },
  { text: "Regeneron eye drug Eylea HD gains significant market share", ticker: "REGN", direction: "long" },
  { text: "Vertex Pharmaceuticals pain drug wins FDA approval", ticker: "VRTX", direction: "long" },
  { text: "Amgen obesity drug shows promising Phase 2 weight loss data", ticker: "AMGN", direction: "long" },
  { text: "Intuitive Surgical da Vinci 5 system drives record procedure growth", ticker: "ISRG", direction: "long" },
  { text: "UnitedHealth beats on earnings as Medicare Advantage enrollment grows", ticker: "UNH", direction: "long" },

  // Software / Cloud / Cyber
  { text: "CrowdStrike wins massive federal cybersecurity contract worth $500M", ticker: "CRWD", direction: "long" },
  { text: "CrowdStrike annual recurring revenue crosses $4B milestone", ticker: "CRWD", direction: "long" },
  { text: "Palantir lands $1B defense contract with US Army", ticker: "PLTR", direction: "long" },
  { text: "Palantir AIP platform drives 55% US commercial revenue growth", ticker: "PLTR", direction: "long" },
  { text: "Shopify merchant volume surges to record levels in holiday quarter", ticker: "SHOP", direction: "long" },
  { text: "ServiceNow raises guidance on accelerating AI product adoption", ticker: "NOW", direction: "long" },
  { text: "Datadog cloud monitoring revenue grows 30% beating estimates", ticker: "DDOG", direction: "long" },
  { text: "Snowflake product revenue accelerates for first time in six quarters", ticker: "SNOW", direction: "long" },
  { text: "Palo Alto Networks wins $400M enterprise security deal", ticker: "PANW", direction: "long" },
  { text: "MongoDB Atlas cloud database revenue surges 40%", ticker: "MDB", direction: "long" },
  { text: "Salesforce AI Einstein copilot drives record deal sizes", ticker: "CRM", direction: "long" },

  // Retail / Consumer
  { text: "Costco same-store sales jump 8% topping all estimates", ticker: "COST", direction: "long" },
  { text: "Walmart raises full-year outlook citing strong consumer spending", ticker: "WMT", direction: "long" },
  { text: "Walmart US ecommerce sales grow 22% in holiday quarter", ticker: "WMT", direction: "long" },
  { text: "Chipotle same-store sales rise 7% on strong traffic growth", ticker: "CMG", direction: "long" },
  { text: "Lululemon international sales surge 35% led by China expansion", ticker: "LULU", direction: "long" },
  { text: "TJX Companies raises dividend 13% after strong off-price quarter", ticker: "TJX", direction: "long" },

  // Energy / Industrial
  { text: "ExxonMobil announces massive Guyana oil discovery", ticker: "XOM", direction: "long" },
  { text: "ExxonMobil Pioneer acquisition drives record Permian Basin output", ticker: "XOM", direction: "long" },
  { text: "Caterpillar backlog hits record $30B on infrastructure spending boom", ticker: "CAT", direction: "long" },
  { text: "GE Aerospace jet engine orders surge 45% on travel demand", ticker: "GE", direction: "long" },
  { text: "Deere raises guidance as precision agriculture adoption accelerates", ticker: "DE", direction: "long" },
  { text: "NextEra Energy signs record 8GW of new renewable contracts", ticker: "NEE", direction: "long" },

  // Other
  { text: "Uber posts first full-year GAAP profit in company history", ticker: "UBER", direction: "long" },
  { text: "Airbnb nights booked surge 18% as international travel booms", ticker: "ABNB", direction: "long" },
  { text: "DraftKings takes market share as sports betting revenue jumps 40%", ticker: "DKNG", direction: "long" },
  { text: "Coinbase crypto trading volume doubles as Bitcoin hits new highs", ticker: "COIN", direction: "long" },
  { text: "Trade Desk connected TV ad spend grows 35% year-over-year", ticker: "TTD", direction: "long" },
  { text: "Arista Networks 400G switch orders surge on AI data center buildout", ticker: "ANET", direction: "long" },
  { text: "Fortinet firewall revenue beats as cybersecurity refresh cycle begins", ticker: "FTNT", direction: "long" },

  // ============================================================
  // BEARISH / SHORT (~80)
  // ============================================================

  // Mega-cap misses
  { text: "Apple China revenue drops 12% as Huawei gains smartphone share", ticker: "AAPL", direction: "short" },
  { text: "Apple warns of slower Services growth due to regulatory pressure", ticker: "AAPL", direction: "short" },
  { text: "Microsoft cloud growth decelerates to 22% missing estimates", ticker: "MSFT", direction: "short" },
  { text: "Alphabet faces DOJ order to divest Chrome browser", ticker: "GOOGL", direction: "short", altTickers: ["GOOG"] },
  { text: "Google loses major antitrust case threatening search monopoly", ticker: "GOOGL", direction: "short", altTickers: ["GOOG"] },
  { text: "Amazon retail margins compress as delivery costs surge", ticker: "AMZN", direction: "short" },
  { text: "Meta faces $1.3B EU fine over data transfer violations", ticker: "META", direction: "short" },
  { text: "Meta monthly active users decline in North America for first time", ticker: "META", direction: "short" },

  // Semiconductors
  { text: "Intel slashes dividend 66% and announces 15,000 layoffs", ticker: "INTC", direction: "short" },
  { text: "Intel foundry business posts $7B operating loss in fiscal year", ticker: "INTC", direction: "short" },
  { text: "NVIDIA faces new US export restrictions on AI chips to China", ticker: "NVDA", direction: "short" },
  { text: "AMD data center GPU revenue misses estimates by wide margin", ticker: "AMD", direction: "short" },
  { text: "Qualcomm warns of significant smartphone inventory correction", ticker: "QCOM", direction: "short" },

  // Healthcare
  { text: "FDA rejects Pfizer's new lung cancer drug application", ticker: "PFE", direction: "short" },
  { text: "Pfizer COVID vaccine demand collapses leading to $5.5B writedown", ticker: "PFE", direction: "short" },
  { text: "Bristol-Myers key cancer drug fails Phase 3 superiority trial", ticker: "BMY", direction: "short" },
  { text: "Moderna slashes 2026 revenue guidance as vaccine demand wanes", ticker: "MRNA", direction: "short" },
  { text: "AbbVie Humira biosimilar competition drives 30% revenue decline", ticker: "ABBV", direction: "short" },
  { text: "Biogen Alzheimer drug Leqembi uptake significantly below expectations", ticker: "BIIB", direction: "short" },
  { text: "CVS Health warns on Medicare Advantage costs cutting full-year outlook", ticker: "CVS", direction: "short" },

  // EV / Auto / Industrial
  { text: "Boeing reports wider-than-expected loss amid delivery delays", ticker: "BA", direction: "short" },
  { text: "Boeing faces new FAA investigation after manufacturing defect found", ticker: "BA", direction: "short" },
  { text: "Ford recalls 500K electric vehicles over battery fire risk", ticker: "F", direction: "short" },
  { text: "Ford EV division loses $4.7B as price war intensifies", ticker: "F", direction: "short" },
  { text: "Tesla misses delivery estimates as EV demand softens globally", ticker: "TSLA", direction: "short" },
  { text: "Tesla China sales drop 15% month-over-month on BYD competition", ticker: "TSLA", direction: "short" },
  { text: "General Motors halts Cruise robotaxi operations after accident", ticker: "GM", direction: "short" },
  { text: "Rivian burns through $1.6B cash in quarter as losses widen", ticker: "RIVN", direction: "short" },
  { text: "Lucid Motors cuts production forecast by 30% on weak demand", ticker: "LCID", direction: "short" },

  // Retail / Consumer
  { text: "Target misses on earnings as consumer spending shifts away from discretionary", ticker: "TGT", direction: "short" },
  { text: "Target shrink losses reach $1.2B forcing store closures", ticker: "TGT", direction: "short" },
  { text: "Nike inventory glut worsens as China sales plummet 20%", ticker: "NKE", direction: "short" },
  { text: "Nike loses market share to On Running and Hoka in key categories", ticker: "NKE", direction: "short" },
  { text: "Starbucks reports first same-store sales decline in four years", ticker: "SBUX", direction: "short" },
  { text: "Starbucks China traffic drops 11% amid consumer boycott", ticker: "SBUX", direction: "short" },
  { text: "Dollar General slashes outlook as low-income consumers pull back", ticker: "DG", direction: "short" },
  { text: "Dollar Tree faces $2B impairment charge on Family Dollar acquisition", ticker: "DLTR", direction: "short" },
  { text: "Lululemon issues weak guidance as athleisure spending cools", ticker: "LULU", direction: "short" },
  { text: "Peloton subscriber count falls below 3 million as churn accelerates", ticker: "PTON", direction: "short" },

  // Tech / Software
  { text: "PayPal loses market share to Apple Pay as active accounts decline", ticker: "PYPL", direction: "short" },
  { text: "Snap warns of significant revenue shortfall citing ad market weakness", ticker: "SNAP", direction: "short" },
  { text: "Snap daily active users miss expectations as TikTok takes share", ticker: "SNAP", direction: "short" },
  { text: "Roku misses revenue estimates as streaming ad market slows", ticker: "ROKU", direction: "short" },
  { text: "Pinterest monthly active users decline for second straight quarter", ticker: "PINS", direction: "short" },
  { text: "Cloudflare issues weak guidance despite beating Q3 estimates", ticker: "NET", direction: "short" },
  { text: "Zoom revenue declines year-over-year as enterprise contracts shrink", ticker: "ZM", direction: "short" },
  { text: "DocuSign loses major enterprise client to Adobe Sign", ticker: "DOCU", direction: "short" },
  { text: "Snowflake consumption growth decelerates sharply to 18%", ticker: "SNOW", direction: "short" },
  { text: "Unity Software lays off 25% of workforce after pricing backlash", ticker: "U", direction: "short" },
  { text: "Shopify misses on merchant growth as SMB spending tightens", ticker: "SHOP", direction: "short" },

  // Financials
  { text: "Bank of America provisions surge on rising consumer loan defaults", ticker: "BAC", direction: "short" },
  { text: "Charles Schwab faces $2B in unrealized bond losses", ticker: "SCHW", direction: "short" },
  { text: "Goldman Sachs takes $800M loss exiting consumer lending business", ticker: "GS", direction: "short" },
  { text: "Regional bank New York Community Bancorp faces deposit outflows", ticker: "NYCB", direction: "short" },

  // Energy / Other
  { text: "Chevron Permian Basin acquisition faces FTC antitrust challenge", ticker: "CVX", direction: "short" },
  { text: "3M faces $10 billion earplug lawsuit settlement", ticker: "MMM", direction: "short" },
  { text: "UPS cuts full-year guidance citing lower package volumes", ticker: "UPS", direction: "short" },
  { text: "FedEx volume decline accelerates as ecommerce growth slows", ticker: "FDX", direction: "short" },
  { text: "Walgreens closes 150 stores as foot traffic continues declining", ticker: "WBA", direction: "short" },
  { text: "SolarEdge issues profit warning as European solar demand collapses", ticker: "SEDG", direction: "short" },
  { text: "Enphase Energy misses on revenue as residential solar installs drop", ticker: "ENPH", direction: "short" },
  { text: "Beyond Meat revenue falls 30% as plant-based trend fades", ticker: "BYND", direction: "short" },

  // ============================================================
  // NEUTRAL / AMBIGUOUS (~40)
  // ============================================================
  { text: "Disney announces strategic review of ESPN and linear TV assets", ticker: "DIS", direction: null },
  { text: "Disney explores strategic options for India streaming business", ticker: "DIS", direction: null },
  { text: "Salesforce to acquire data analytics startup for $8 billion", ticker: "CRM", direction: null },
  { text: "Johnson & Johnson announces plan to spin off consumer health division", ticker: "JNJ", direction: null },
  { text: "Uber explores partnership with Waymo for autonomous ride-hailing", ticker: "UBER", direction: null },
  { text: "Berkshire Hathaway discloses new undisclosed position in quarterly filing", ticker: "BRK.B", direction: null, altTickers: ["BRK.A", "BRK"] },
  { text: "Adobe shifts pricing model to consumption-based for Creative Cloud", ticker: "ADBE", direction: null },
  { text: "Visa faces DOJ antitrust lawsuit over debit card market dominance", ticker: "V", direction: null },
  { text: "ServiceNow CEO steps down effective immediately, COO named interim", ticker: "NOW", direction: null },
  { text: "Coinbase receives Wells notice from SEC over staking products", ticker: "COIN", direction: null },
  { text: "Marathon Petroleum announces $5 billion share buyback program", ticker: "MPC", direction: null },
  { text: "T-Mobile and Sprint merger integration hits final milestone", ticker: "TMUS", direction: null },
  { text: "Block Inc restructures into two independent divisions", ticker: "SQ", direction: null },
  { text: "ConocoPhillips in advanced merger talks with Marathon Oil", ticker: "COP", direction: null },
  { text: "Lockheed Martin wins $2B contract but faces supply chain delays", ticker: "LMT", direction: null },
  { text: "General Electric completes three-way split into separate public companies", ticker: "GE", direction: null },
  { text: "Intel explores strategic alternatives including potential foundry spinoff", ticker: "INTC", direction: null },
  { text: "Paramount agrees to merge with Skydance in $28B deal", ticker: "PARA", direction: null },
  { text: "Activision Blizzard merger with Microsoft clears final regulatory hurdle", ticker: "MSFT", direction: null },
  { text: "Exxon and Chevron both bid on same $10B offshore asset", ticker: "XOM", direction: null },
  { text: "Kroger-Albertsons merger faces state attorney general challenge", ticker: "KR", direction: null },
  { text: "US Steel rejects Nippon Steel acquisition offer on national security concerns", ticker: "X", direction: null },
  { text: "HashiCorp agrees to $5.7B acquisition by IBM", ticker: "HCP", direction: null },
  { text: "Figma acquisition by Adobe falls apart due to regulatory pressure", ticker: "ADBE", direction: null },
  { text: "Spirit Airlines files for Chapter 11 bankruptcy protection", ticker: "SAVE", direction: null },
  { text: "Bed Bath & Beyond emerges from bankruptcy under new ownership", ticker: "BBBY", direction: null },
  { text: "WeWork exits bankruptcy with restructured $4B debt load", ticker: "WE", direction: null },
  { text: "Elliott Management takes activist stake in Texas Instruments", ticker: "TXN", direction: null },
  { text: "Carl Icahn discloses 8% stake in Illumina pushing for board changes", ticker: "ILMN", direction: null },
  { text: "Starboard Value pushes for strategic review at Autodesk", ticker: "ADSK", direction: null },
  { text: "Apple reportedly in talks to invest $1B in OpenAI", ticker: "AAPL", direction: null },
  { text: "Amazon considers spinning off pharmacy business as standalone unit", ticker: "AMZN", direction: null },
  { text: "Tesla announces 5-for-1 stock split effective next month", ticker: "TSLA", direction: null },
  { text: "Broadcom completes VMware integration ahead of schedule", ticker: "AVGO", direction: null },
  { text: "Oracle moves headquarters from Texas to Nashville", ticker: "ORCL", direction: null },
  { text: "Netflix announces plan to stop reporting subscriber numbers", ticker: "NFLX", direction: null },
  { text: "Meta launches standalone AI assistant app competing with ChatGPT", ticker: "META", direction: null },
  { text: "Stripe confidentially files for IPO expected in second half", ticker: "STRIP", direction: null },
  { text: "Reddit IPO prices at $34 per share valuing company at $6.5B", ticker: "RDDT", direction: null },
];

// Noise headlines — not actionable, correct response is to skip (Del)
window.NOISE_HEADLINES = [
  // Macro / market-wide noise
  { text: "US consumer confidence index comes in at 104.2 for March", ticker: "", noise: true },
  { text: "Fed officials reiterate data-dependent approach to rate decisions", ticker: "", noise: true },
  { text: "Treasury yields hold steady ahead of Friday jobs report", ticker: "", noise: true },
  { text: "Oil prices little changed as traders await OPEC meeting", ticker: "", noise: true },
  { text: "European markets close mixed in quiet trading session", ticker: "", noise: true },
  { text: "China manufacturing PMI ticks up to 50.3 in March", ticker: "", noise: true },
  { text: "Dollar index flat as markets digest mixed economic signals", ticker: "", noise: true },
  { text: "Weekly jobless claims come in at 215K matching expectations", ticker: "", noise: true },
  { text: "IMF maintains global growth forecast at 3.1% for 2026", ticker: "", noise: true },
  { text: "Gold prices consolidate near $2,400 amid low volatility", ticker: "", noise: true },
  { text: "Natural gas inventories draw 28 Bcf in line with estimates", ticker: "", noise: true },
  { text: "Senate committee schedules hearing on AI regulation framework", ticker: "", noise: true },
  { text: "US trade deficit widens slightly to $68.9B in January", ticker: "", noise: true },
  { text: "US housing starts rise 1.2% month-over-month in February", ticker: "", noise: true },
  { text: "Bitcoin trades sideways around $95K over the weekend", ticker: "", noise: true },
  { text: "10-year Treasury note auction sees solid demand from foreign buyers", ticker: "", noise: true },
  { text: "Copper futures edge higher on steady Chinese construction activity", ticker: "", noise: true },
  { text: "VIX remains below 15 signaling continued low market volatility", ticker: "", noise: true },
  { text: "S&P 500 ends day flat as investors await CPI data Wednesday", ticker: "", noise: true },
  { text: "ECB holds interest rates steady at 4.5% as expected", ticker: "", noise: true },

  // Company-specific noise — mentions a ticker but not actionable
  { text: "Apple announces new color options for iPhone 16 lineup", ticker: "", noise: true },
  { text: "Apple updates App Store guidelines for subscription pricing display", ticker: "", noise: true },
  { text: "Tesla opens two new Supercharger stations in rural Texas", ticker: "", noise: true },
  { text: "Tesla Cybertruck spotted testing new wheel design in Fremont", ticker: "", noise: true },
  { text: "Amazon updates return policy for third-party sellers", ticker: "", noise: true },
  { text: "Amazon opens new same-day delivery hub in suburban Atlanta", ticker: "", noise: true },
  { text: "Microsoft releases minor patch update for Windows 11", ticker: "", noise: true },
  { text: "Microsoft Teams adds new whiteboard collaboration features", ticker: "", noise: true },
  { text: "NVIDIA CEO Jensen Huang to speak at tech conference next week", ticker: "", noise: true },
  { text: "NVIDIA releases new GeForce driver update for gaming GPUs", ticker: "", noise: true },
  { text: "Meta updates community guidelines for Instagram Threads", ticker: "", noise: true },
  { text: "Meta opens new AI research lab in Paris", ticker: "", noise: true },
  { text: "Alphabet publishes annual diversity and inclusion report", ticker: "", noise: true },
  { text: "Google Maps adds new EV charging station finder feature", ticker: "", noise: true },
  { text: "JPMorgan opens new branch location in downtown Nashville", ticker: "", noise: true },
  { text: "JPMorgan publishes annual letter to shareholders", ticker: "", noise: true },
  { text: "Disney announces new meet-and-greet character at Magic Kingdom", ticker: "", noise: true },
  { text: "Disney Plus adds new parental control features", ticker: "", noise: true },
  { text: "Netflix adds behind-the-scenes content for popular series", ticker: "", noise: true },
  { text: "Netflix expands mobile games library with three new titles", ticker: "", noise: true },
  { text: "Boeing completes routine maintenance inspection on 737 fleet", ticker: "", noise: true },
  { text: "Walmart expands grocery delivery hours to include early morning", ticker: "", noise: true },
  { text: "Walmart rolls out new self-checkout kiosk design in 200 stores", ticker: "", noise: true },
  { text: "Costco opens new warehouse location in suburban Phoenix", ticker: "", noise: true },
  { text: "Nike releases limited edition colorway for Air Max line", ticker: "", noise: true },
  { text: "Nike signs new sponsorship deal with college basketball team", ticker: "", noise: true },
  { text: "Starbucks introduces new seasonal drink to spring menu", ticker: "", noise: true },
  { text: "Starbucks redesigns mobile app order tracking interface", ticker: "", noise: true },
  { text: "AMD sponsors esports tournament at DreamHack event", ticker: "", noise: true },
  { text: "Uber adds new accessibility features to rider app", ticker: "", noise: true },
  { text: "Uber expands electric bike sharing program to three new cities", ticker: "", noise: true },
  { text: "Pfizer donates $5M to global health initiative in Africa", ticker: "", noise: true },
  { text: "Goldman Sachs publishes research note on emerging market trends", ticker: "", noise: true },
  { text: "CrowdStrike CEO to participate in fireside chat at RSA Conference", ticker: "", noise: true },
  { text: "Salesforce hosts annual Dreamforce conference in San Francisco", ticker: "", noise: true },
  { text: "Intel CEO presents at CES keynote showcasing upcoming products", ticker: "", noise: true },
  { text: "Ford announces Heritage Edition package for F-150 pickup", ticker: "", noise: true },
  { text: "Target launches new private label organic food brand", ticker: "", noise: true },
  { text: "Visa partners with FIFA for payment processing at World Cup", ticker: "", noise: true },
  { text: "Eli Lilly sponsors diabetes awareness campaign during health week", ticker: "", noise: true },
  { text: "Broadcom updates enterprise software documentation portal", ticker: "", noise: true },
  { text: "Palantir publishes blog post on government AI use cases", ticker: "", noise: true },
  { text: "Shopify hosts annual partner conference in Toronto", ticker: "", noise: true },
  { text: "Netflix documentary about climate change wins Emmy nomination", ticker: "", noise: true },
  { text: "Tesla releases holiday software update with new games and features", ticker: "", noise: true },
];
