window.DEFAULT_HEADLINES = [
  // === BULLISH / LONG ===
  { text: "Apple reports record Q3 revenue beating Wall Street estimates", ticker: "AAPL", direction: "long" },
  { text: "NVIDIA raises full-year guidance on surging AI chip demand", ticker: "NVDA", direction: "long" },
  { text: "Tesla delivers record 500K vehicles in Q4 exceeding expectations", ticker: "TSLA", direction: "long" },
  { text: "Amazon Web Services revenue jumps 35% year-over-year", ticker: "AMZN", direction: "long" },
  { text: "Microsoft beats on both top and bottom line, cloud growth accelerates", ticker: "MSFT", direction: "long" },
  { text: "Meta Platforms ad revenue surges 25% as Reels monetization ramps", ticker: "META", direction: "long" },
  { text: "Alphabet reports blowout earnings driven by Google Cloud growth", ticker: "GOOGL", direction: "long", altTickers: ["GOOG"] },
  { text: "Netflix adds 13 million subscribers crushing analyst forecasts", ticker: "NFLX", direction: "long" },
  { text: "JPMorgan reports record annual profit on strong trading revenue", ticker: "JPM", direction: "long" },
  { text: "Eli Lilly obesity drug shows 25% weight loss in late-stage trial", ticker: "LLY", direction: "long" },
  { text: "CrowdStrike wins massive federal cybersecurity contract worth $500M", ticker: "CRWD", direction: "long" },
  { text: "Costco same-store sales jump 8% topping all estimates", ticker: "COST", direction: "long" },
  { text: "AMD secures major AI chip deal with Microsoft Azure", ticker: "AMD", direction: "long" },
  { text: "Walmart raises full-year outlook citing strong consumer spending", ticker: "WMT", direction: "long" },
  { text: "Broadcom reports blowout quarter on AI networking chip demand", ticker: "AVGO", direction: "long" },
  { text: "Palantir lands $1B defense contract with US Army", ticker: "PLTR", direction: "long" },
  { text: "Goldman Sachs trading revenue surges 40% in volatile markets", ticker: "GS", direction: "long" },
  { text: "Moderna flu-COVID combo vaccine shows strong Phase 3 results", ticker: "MRNA", direction: "long" },
  { text: "ExxonMobil announces massive Guyana oil discovery", ticker: "XOM", direction: "long" },
  { text: "Shopify merchant volume surges to record levels in holiday quarter", ticker: "SHOP", direction: "long" },

  // === BEARISH / SHORT ===
  { text: "FDA rejects Pfizer's new lung cancer drug application", ticker: "PFE", direction: "short" },
  { text: "Boeing reports wider-than-expected loss amid delivery delays", ticker: "BA", direction: "short" },
  { text: "Intel slashes dividend 66% and announces 15,000 layoffs", ticker: "INTC", direction: "short" },
  { text: "Target misses on earnings as consumer spending shifts away from discretionary", ticker: "TGT", direction: "short" },
  { text: "PayPal loses market share to Apple Pay as active accounts decline", ticker: "PYPL", direction: "short" },
  { text: "Snap warns of significant revenue shortfall citing ad market weakness", ticker: "SNAP", direction: "short" },
  { text: "Roku misses revenue estimates as streaming ad market slows", ticker: "ROKU", direction: "short" },
  { text: "3M faces $10 billion earplug lawsuit settlement", ticker: "MMM", direction: "short" },
  { text: "Nike inventory glut worsens as China sales plummet 20%", ticker: "NKE", direction: "short" },
  { text: "Starbucks reports first same-store sales decline in four years", ticker: "SBUX", direction: "short" },
  { text: "Bristol-Myers key cancer drug fails Phase 3 superiority trial", ticker: "BMY", direction: "short" },
  { text: "UPS cuts full-year guidance citing lower package volumes", ticker: "UPS", direction: "short" },
  { text: "Chevron Permian Basin acquisition faces FTC antitrust challenge", ticker: "CVX", direction: "short" },
  { text: "Pinterest monthly active users decline for second straight quarter", ticker: "PINS", direction: "short" },
  { text: "Bank of America provisions surge on rising consumer loan defaults", ticker: "BAC", direction: "short" },
  { text: "Dollar General slashes outlook as low-income consumers pull back", ticker: "DG", direction: "short" },
  { text: "AbbVie Humira biosimilar competition drives 30% revenue decline", ticker: "ABBV", direction: "short" },
  { text: "Ford recalls 500K electric vehicles over battery fire risk", ticker: "F", direction: "short" },
  { text: "Cloudflare issues weak guidance despite beating Q3 estimates", ticker: "NET", direction: "short" },

  // === NEUTRAL / AMBIGUOUS ===
  { text: "Disney announces strategic review of ESPN and linear TV assets", ticker: "DIS", direction: null },
  { text: "Salesforce to acquire data analytics startup for $8 billion", ticker: "CRM", direction: null },
  { text: "Johnson & Johnson announces plan to spin off consumer health division", ticker: "JNJ", direction: null },
  { text: "Uber explores partnership with Waymo for autonomous ride-hailing", ticker: "UBER", direction: null },
  { text: "Berkshire Hathaway discloses new undisclosed position in quarterly filing", ticker: "BRK.B", direction: null, altTickers: ["BRK.A", "BRK"] },
  { text: "General Electric completes three-way split into separate public companies", ticker: "GE", direction: null },
  { text: "Adobe shifts pricing model to consumption-based for Creative Cloud", ticker: "ADBE", direction: null },
  { text: "Visa faces DOJ antitrust lawsuit over debit card market dominance", ticker: "V", direction: null },
  { text: "ServiceNow CEO steps down effective immediately, COO named interim", ticker: "NOW", direction: null },
  { text: "Coinbase receives Wells notice from SEC over staking products", ticker: "COIN", direction: null },
  { text: "Marathon Petroleum announces $5 billion share buyback program", ticker: "MPC", direction: null },
  { text: "T-Mobile and Sprint merger integration hits final milestone", ticker: "TMUS", direction: null },
  { text: "Block Inc restructures into two independent divisions", ticker: "SQ", direction: null },
  { text: "Micron announces $15 billion Idaho chip manufacturing plant", ticker: "MU", direction: null },
  { text: "ConocoPhillips in advanced merger talks with Marathon Oil", ticker: "COP", direction: null },
  { text: "Lockheed Martin wins $2B contract but faces supply chain delays", ticker: "LMT", direction: null },
];

// Noise headlines — not actionable, correct response is to skip (Del)
window.NOISE_HEADLINES = [
  // Macro / market-wide noise
  { text: "US consumer confidence index comes in at 104.2 for March", ticker: "", noise: true },
  { text: "Fed officials reiterate data-dependent approach to rate decisions", ticker: "", noise: true },
  { text: "Treasury yields hold steady ahead of Friday jobs report", ticker: "", noise: true },
  { text: "Oil prices little changed as traders await OPEC meeting", ticker: "", noise: true },
  { text: "European markets close mixed in quiet trading session", ticker: "", noise: true },
  { text: "China manufacturing PMI ticks up to 50.3 in March", ticker: "", noise: true },
  { text: "Dollar index flat as markets digest mixed economic signals", ticker: "", noise: true },
  { text: "Weekly jobless claims come in at 215K matching expectations", ticker: "", noise: true },
  { text: "IMF maintains global growth forecast at 3.1% for 2026", ticker: "", noise: true },
  { text: "Gold prices consolidate near $2,400 amid low volatility", ticker: "", noise: true },
  { text: "Natural gas inventories draw 28 Bcf in line with estimates", ticker: "", noise: true },
  { text: "Senate committee schedules hearing on AI regulation framework", ticker: "", noise: true },
  { text: "US trade deficit widens slightly to $68.9B in January", ticker: "", noise: true },

  // Company-specific noise — mentions a ticker but not actionable
  { text: "Apple announces new color options for iPhone 16 lineup", ticker: "", noise: true },
  { text: "Tesla opens two new Supercharger stations in rural Texas", ticker: "", noise: true },
  { text: "Amazon updates return policy for third-party sellers", ticker: "", noise: true },
  { text: "Microsoft releases minor patch update for Windows 11", ticker: "", noise: true },
  { text: "NVIDIA CEO Jensen Huang to speak at tech conference next week", ticker: "", noise: true },
  { text: "Meta updates community guidelines for Instagram Threads", ticker: "", noise: true },
  { text: "Alphabet publishes annual diversity and inclusion report", ticker: "", noise: true },
  { text: "JPMorgan opens new branch location in downtown Nashville", ticker: "", noise: true },
  { text: "Disney announces new meet-and-greet character at Magic Kingdom", ticker: "", noise: true },
  { text: "Netflix adds behind-the-scenes content for popular series", ticker: "", noise: true },
  { text: "Boeing completes routine maintenance inspection on 737 fleet", ticker: "", noise: true },
  { text: "Walmart expands grocery delivery hours to include early morning", ticker: "", noise: true },
  { text: "Costco opens new warehouse location in suburban Phoenix", ticker: "", noise: true },
  { text: "Nike releases limited edition colorway for Air Max line", ticker: "", noise: true },
  { text: "Starbucks introduces new seasonal drink to spring menu", ticker: "", noise: true },
  { text: "AMD sponsors esports tournament at DreamHack event", ticker: "", noise: true },
  { text: "Uber adds new accessibility features to rider app", ticker: "", noise: true },
  { text: "Pfizer donates $5M to global health initiative in Africa", ticker: "", noise: true },
  { text: "Goldman Sachs publishes research note on emerging market trends", ticker: "", noise: true },
  { text: "CrowdStrike CEO to participate in fireside chat at RSA Conference", ticker: "", noise: true },
];
